// --- 1. Master Data Definitions ---

const bacteriaLibrary = [
    { name: "Escherichia coli (E.coli)", code: "ECO", group: "Gram-Negative" },
    { name: "Klebsiella pneumoniae", code: "KPN", group: "Gram-Negative" },
    { name: "Klebsiella oxytoca", code: "KOX", group: "Gram-Negative" },
    { name: "Klebsiella aerogenes", code: "KAE", group: "Gram-Negative" },
    { name: "Enterobacter cloacae", code: "ECL", group: "Gram-Negative" },
    { name: "Enterobacter (spp)", code: "ENT", group: "Gram-Negative" },
    { name: "Proteus mirabilis", code: "PMI", group: "Gram-Negative" },
    { name: "Proteus vulgaris", code: "PVU", group: "Gram-Negative" },
    { name: "Proteus (other spp)", code: "PRO", group: "Gram-Negative" },
    { name: "Morganella morganii", code: "MMO", group: "Gram-Negative" },
    { name: "Providencia stuartii", code: "PST", group: "Gram-Negative" },
    { name: "Providencia rettgeri", code: "PRE", group: "Gram-Negative" },
    { name: "Providencia spp", code: "PRV", group: "Gram-Negative" },
    { name: "Serratia marcescens", code: "SMA", group: "Gram-Negative" },
    { name: "Serratia spp", code: "SER", group: "Gram-Negative" },
    { name: "Citrobacter freundii", code: "CFR", group: "Gram-Negative" },
    { name: "Citrobacter koseri", code: "CKO", group: "Gram-Negative" },
    { name: "Citrobacter (spp)", code: "CIT", group: "Gram-Negative" },
    { name: "Salmonella Typhi", code: "STY", group: "Gram-Negative" },
    { name: "Salmonella Typhimurium", code: "STM", group: "Gram-Negative" },
    { name: "Salmonella Enteritidis", code: "SEN", group: "Gram-Negative" },
    { name: "Salmonella spp", code: "SAL", group: "Gram-Negative" },
    { name: "Shigella sonnei", code: "SSO", group: "Gram-Negative" },
    { name: "Shigella flexneri", code: "SFL", group: "Gram-Negative" },
    { name: "Shigella dysenteriae", code: "SDY", group: "Gram-Negative" },
    { name: "Shigella (spp)", code: "SHI", group: "Gram-Negative" },
    { name: "Yersinia enterocolitica", code: "YEN", group: "Gram-Negative" },
    { name: "Enterobacteriaceae (other spp)", code: "EBO", group: "Gram-Negative" },
    { name: "Pseudomonas aeruginosa", code: "PAE", group: "Gram-Negative" },
    { name: "Pseudomonas putida", code: "PPU", group: "Gram-Negative" },
    { name: "Acinetobacter baumannii", code: "ABA", group: "Gram-Negative" },
    { name: "Acinetobacter lwoffii", code: "ALW", group: "Gram-Negative" },
    { name: "Acinetobacter spp.", code: "ACI", group: "Gram-Negative" },
    { name: "Stenotrophomonas maltophilia", code: "SML", group: "Gram-Negative" },
    { name: "Burkholderia cepacia complex", code: "BCC", group: "Gram-Negative" },
    { name: "Haemophilus influenzae", code: "HIN", group: "Gram-Negative" },
    { name: "Haemophilus parainfluenzae", code: "HPA", group: "Gram-Negative" },
    { name: "Neisseria gonorrhoeae", code: "NGO", group: "Gram-Negative" },
    { name: "Neisseria meningitidis", code: "NME", group: "Gram-Negative" },
    { name: "Moraxella catarrhalis", code: "MCA", group: "Gram-Negative" },
    { name: "Campylobacter jejuni", code: "CJE", group: "Gram-Negative" },
    { name: "Helicobacter pylori", code: "HPY", group: "Gram-Negative" },
    { name: "Vibrio cholerae", code: "VCH", group: "Gram-Negative" },
    { name: "Brucella melitensis", code: "BME", group: "Gram-Negative" },
    { name: "Brucella abortus", code: "BAB", group: "Gram-Negative" },
    { name: "Bacteroides fragilis", code: "BFR", group: "Gram-Negative" },
    { name: "Legionella pneumophila", code: "LPN", group: "Gram-Negative" },
    { name: "Chlamydia trachomatis", code: "CTR", group: "Gram-Negative" },
    { name: "Fusobacterium canifelinum", code: "FCA", group: "Gram-Negative" },
    { name: "Staphylococcus aureus", code: "SAU", group: "Gram-Positive" },
    { name: "Staphylococcus epidermidis", code: "SEP", group: "Gram-Positive" },
    { name: "Staphylococcus saprophyticus", code: "SSP", group: "Gram-Positive" },
    { name: "Staphylococcus haemolyticus", code: "SHM", group: "Gram-Positive" },
    { name: "Staphylococcus hominis", code: "SHO", group: "Gram-Positive" },
    { name: "Staphylococcus lugdunensis", code: "SLG", group: "Gram-Positive" },
    { name: "Staphylococcus non-aureus (spp) / CoNS", code: "CNS", group: "Gram-Positive" },
    { name: "Streptococcus pneumoniae", code: "SPN", group: "Gram-Positive" },
    { name: "Streptococcus pyogenes (Group A)", code: "SPY", group: "Gram-Positive" },
    { name: "Streptococcus agalactiae (Group B)", code: "SAG", group: "Gram-Positive" },
    { name: "Streptococcus mutans", code: "SMU", group: "Gram-Positive" },
    { name: "Streptococcus spp (β-hemolytic group)", code: "SBH", group: "Gram-Positive" },
    { name: "Streptococcus viridans", code: "SVI", group: "Gram-Positive" },
    { name: "Enterococcus faecalis", code: "EFA", group: "Gram-Positive" },
    { name: "Enterococcus faecium", code: "EFM", group: "Gram-Positive" },
    { name: "Enterococcus gallinarum / E. casseliflavus", code: "EGC", group: "Gram-Positive" },
    { name: "Enterococcus spp", code: "ENC", group: "Gram-Positive" },
    { name: "Listeria monocytogenes", code: "LMO", group: "Gram-Positive" },
    { name: "Listeria spp", code: "LIS", group: "Gram-Positive" },
    { name: "Corynebacterium diphtheriae", code: "CDI", group: "Gram-Positive" },
    { name: "Corynebacterium jeikeium", code: "CJE", group: "Gram-Positive" },
    { name: "Bacillus cereus", code: "BCE", group: "Gram-Positive" },
    { name: "Bacillus anthracis", code: "BAN", group: "Gram-Positive" },
    { name: "Bacillus spp", code: "BAC", group: "Gram-Positive" },
    { name: "Clostridium perfringens", code: "CPE", group: "Gram-Positive" },
    { name: "Clostridioides difficile", code: "CDF", group: "Gram-Positive" },
    { name: "Clostridium tetani", code: "CTE", group: "Gram-Positive" },
    { name: "Clostridium Spp", code: "CLO", group: "Gram-Positive" },
    { name: "Cutibacterium acnes", code: "CAC", group: "Gram-Positive" },
    { name: "Mycobacterium tuberculosis", code: "MTB", group: "Others" },
    { name: "Mycoplasma pneumoniae", code: "MPN", group: "Others" },
    { name: "Anaerobes (General)", code: "ANA", group: "Others" },
    { name: "Candida albicans", code: "CAL", group: "Fungi" },
    { name: "Candida auris", code: "CAU", group: "Fungi" }
];

const abxGroups = {
    "Penicillins": ["Benzylpenicillin", "Penicillin", "Ampicillin", "Amoxicillin", "Cloxacillin", "Oxacillin", "Amoxicillin/Clavulanic acid", "Ampicillin/Sulbactam", "Piperacillin", "Piperacillin/Tazobactam", "Ticarcillin", "Ticarcillin/Clavulanic acid"],
    "Cephalosporins": ["Cefazolin", "Cefoxitin", "Cefuroxime", "Cefixime", "Ceftriaxone", "Cefotaxime", "Ceftazidime", "Cefepime", "Cefaclor", "Cefpodoxime", "Cefdinir", "Cephalothin", "Cefoxitin screen"],
    "Carbapenems & Monobactams": ["Imipenem", "Meropenem", "Ertapenem", "Aztreonam"],
    "Aminoglycosides": ["Amikacin", "Gentamicin", "Tobramycin", "Netilmicin"],
    "Fluoroquinolones": ["Nalidixic acid", "Ciprofloxacin", "Levofloxacin", "Moxifloxacin", "Ofloxacin", "Norfloxacin"],
    "Macrolides & Lincosamides": ["Erythromycin", "Azithromycin", "Clarithromycin", "Clindamycin", "Inducible Clindamycin Resistance"],
    "Glycopeptides": ["Vancomycin", "Teicoplanin", "Daptomycin"],
    "Tetracyclines": ["Tetracycline", "Doxycycline", "Tigecycline"],
    "Others": ["Trimethoprim/Sulfamethoxazole", "Trimethoprim", "Nitrofurantoin", "Fosfomycin", "Colistin", "Linezolid", "Rifampicin", "Fusidic acid", "Mupirocin"],
    "Antifungals": []
};

const abxList = Object.values(abxGroups).flat();

const abxMapExport = {
    "Ampicillin": {t:4, r:5}, "Flucloxacillin": {t:7, r:8}, "Penicillin": {t:10, r:11},
    "Ampicillin/Sulbactam": {t:13, r:14}, "Amoxicillin": {t:16, r:17}, "Oxacillin": {t:19, r:20},
    "Amoxicillin/Clavulanic acid": {t:22, r:23}, "Piperacillin": {t:25, r:26}, "Ticarcillin": {t:28, r:29},
    "Ticarcillin/Clavulanic acid": {t:31, r:32}, "Piperacillin/Tazobactam": {t:34, r:35},
    "Ceftriaxone": {t:37, r:38}, "Cefotaxime": {t:40, r:41}, "Ceftazidime": {t:43, r:44},
    "Cefepime": {t:46, r:47}, "Cefoxitin": {t:49, r:50}, "Cefazolin": {t:52, r:53}, "Cefixime": {t:55, r:56},
    "Cefaclor": {t:58, r:59}, "Cefpodoxime": {t:61, r:62}, "Cefdinir": {t:64, r:65}, "Cephalothin": {t:67, r:68},
    "Cefuroxime": {t:70, r:71}, "Amikacin": {t:73, r:74}, "Gentamicin": {t:76, r:77},
    "Tobramycin": {t:79, r:80}, "Netilmicin": {t:82, r:83}, "Imipenem": {t:85, r:86},
    "Meropenem": {t:88, r:89}, "Ertapenem": {t:91, r:92}, "Aztreonam": {t:94, r:95},
    "Azithromycin": {t:97, r:98}, "Clarithromycin": {t:100, r:101}, "Erythromycin": {t:103, r:104},
    "Ciprofloxacin": {t:106, r:107}, "Moxifloxacin": {t:109, r:110}, "Levofloxacin": {t:112, r:113},
    "Teicoplanin": {t:115, r:116}, "Vancomycin": {t:118, r:119}, "Tigecycline": {t:121, r:122},
    "Tetracycline": {t:124, r:125}, "Doxycycline": {t:127, r:128}, "Colistin": {t:130, r:131},
    "Chloramphenicol": {t:133, r:134}, "Trimethoprim/Sulfamethoxazole": {t:136, r:137},
    "Rifampicin": {t:139, r:140}, "Nitrofurantoin": {t:142, r:143}, "Trimethoprim": {t:145, r:146},
    "Sulfisoxazole": {t:148, r:149}, "Fosfomycin": {t:151, r:152}, "Clindamycin": {t:154, r:155},
    "Metronidazole": {t:157, r:158}, "Fusidic acid": {t:160, r:161}
};

const orgMapExport = {
    "E.coli": 6, "klebsiella pneumoniae": 7, "proteus mirabillis": 8, "proteus (other spp)": 9, 
    "citrobacter (spp)": 10, "enterobacter (spp)": 11, "providencia spp": 12, "salmonella spp": 13, 
    "shigella (spp)": 14, "serratia": 15, "yersinia enterocoliticae": 16, "enterobacteriaceae (other spp)": 17,
    "acinetobacter baumannii": 18, "acinetobacter spp.": 19, "burkholderia cepacia complex": 20,
    "pseudomonas aeruginosa": 21, "hemophilus influenzae": 22, "neisseria gonorrhoeae": 23,
    "neisseria meningitis": 24, "bacteroides fragilis": 25, "chlamydia trachomatis": 26,
    "helicobacter pylori": 27, "Fusobacterium canifelinum": 28, "staphylococcus aureus": 29,
    "staphylococcus non-aureus (spp)": 30, "streptococcus pneumoniae": 31,
    "streptococcus pyogenes (groupnA)": 32, "listeria": 33, "clostridium Spp": 34,
    "bacillus": 35, "enterococcus faecalis": 36, "enterococcus spp": 37,
    "mycobacterium tuberculosis": 38, "streptococcus spp (β-hemolytic group)": 39,
    "streptococcus viridans": 40, "anaerobes": 41, "Enterococcus faecium": 42,
    "Enterococcus gallinarum/E. casseliflavus": 43
};

const defaultSamples = ["Blood", "Urine", "Sputum", "Wound Swab", "CSF", "Pus", "Stool", "Aspirate"];
const defaultWards = ["Pediatrics", "Resuscitation / CCU", "Internal Medicine", "General Surgery", "Private Ward", "Neonatal Unit", "NICU", "ICU", "General Obstetrics & Gynecology", "Private Obstetrics & Gynecology", "Neurology & Neurosurgery", "Delivery Room", "Orthopedics"];

// WHONET Fallback Mapping
const whonetOrgMap = {
    "eco": "Escherichia coli (E.coli)", "kpn": "Klebsiella pneumoniae", "kox": "Klebsiella oxytoca", 
    "kae": "Klebsiella aerogenes", "ecl": "Enterobacter cloacae", "ent": "Enterobacter (spp)", 
    "pmi": "Proteus mirabilis", "pvu": "Proteus vulgaris", "pro": "Proteus (other spp)", 
    "mmo": "Morganella morganii", "pst": "Providencia stuartii", "pre": "Providencia rettgeri", 
    "prv": "Providencia spp", "sma": "Serratia marcescens", "ser": "Serratia spp", 
    "cfr": "Citrobacter freundii", "cko": "Citrobacter koseri", "cit": "Citrobacter (spp)", 
    "sty": "Salmonella Typhi", "stm": "Salmonella Typhimurium", "sen": "Salmonella Enteritidis", 
    "sal": "Salmonella spp", "sso": "Shigella sonnei", "sfl": "Shigella flexneri", 
    "sdy": "Shigella dysenteriae", "shi": "Shigella (spp)", "yen": "Yersinia enterocolitica", 
    "ebo": "Enterobacteriaceae (other spp)", "pae": "Pseudomonas aeruginosa", "ppu": "Pseudomonas putida", 
    "aba": "Acinetobacter baumannii", "alw": "Acinetobacter lwoffii", "aci": "Acinetobacter spp.", 
    "sml": "Stenotrophomonas maltophilia", "bcc": "Burkholderia cepacia complex", "hin": "Haemophilus influenzae", 
    "hpa": "Haemophilus parainfluenzae", "ngo": "Neisseria gonorrhoeae", "nme": "Neisseria meningitidis", 
    "mca": "Moraxella catarrhalis", "cje": "Campylobacter jejuni", "hpy": "Helicobacter pylori", 
    "vch": "Vibrio cholerae", "bme": "Brucella melitensis", "bab": "Brucella abortus", 
    "bfr": "Bacteroides fragilis", "lpn": "Legionella pneumophila", "ctr": "Chlamydia trachomatis", 
    "fca": "Fusobacterium canifelinum", "sau": "Staphylococcus aureus", "sep": "Staphylococcus epidermidis", 
    "ssp": "Staphylococcus saprophyticus", "shm": "Staphylococcus haemolyticus", "sho": "Staphylococcus hominis", 
    "slg": "Staphylococcus lugdunensis", "cns": "Staphylococcus non-aureus (spp) / CoNS", "sta": "Staphylococcus spp", 
    "spn": "Streptococcus pneumoniae", "spy": "Streptococcus pyogenes (Group A)", "sag": "Streptococcus agalactiae (Group B)", 
    "smu": "Streptococcus mutans", "sbh": "Streptococcus spp (β-hemolytic group)", "svi": "Streptococcus viridans", 
    "efa": "Enterococcus faecalis", "efm": "Enterococcus faecium", "egc": "Enterococcus gallinarum / E. casseliflavus", 
    "enc": "Enterococcus spp", "lmo": "Listeria monocytogenes", "lis": "Listeria spp", 
    "cdi": "Corynebacterium diphtheriae", "bce": "Bacillus cereus", "ban": "Bacillus anthracis", 
    "bac": "Bacillus spp", "cpe": "Clostridium perfringens", "cdf": "Clostridioides difficile", 
    "cte": "Clostridium tetani", "clo": "Clostridium Spp", "cac": "Cutibacterium acnes",
    "mtb": "Mycobacterium tuberculosis", "mpn": "Mycoplasma pneumoniae", "ana": "Anaerobes (General)", 
    "cal": "Candida albicans", "cau": "Candida auris", "cgl": "Candida glabrata", "cpa": "Candida parapsilosis",
    "eae": "Enterobacter aerogenes", "cfr": "Citrobacter freundii", 
    "ckr": "Citrobacter koseri", "sca": "Staphylococcus capitis"
};